//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project_FT1KIW.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Species { get; set; }
        public Nullable<int> Age { get; set; }
        public string Problem { get; set; }
        public string Treatment { get; set; }
        public string Doctor { get; set; }
    }
}
